[package]
name = "farm3"
version = "0.0.1"

[dependencies]
AptosFramework = {git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet"}

[addresses]
kepler = "_"
